# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('key', models.BooleanField()),
                ('notes', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='DescribedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('hidden', models.BooleanField()),
                ('name', models.CharField(max_length=64)),
                ('key', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HappenedAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Involved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Character')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='happenedat',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Location'),
        ),
        migrations.AddField(
            model_name='describedby',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Description'),
        ),
        migrations.AddField(
            model_name='describedby',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Event'),
        ),
    ]
