# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_remove_event_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='file_name',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='author',
            field=models.CharField(max_length=32),
        ),
    ]
