# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20160327_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
