# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20160327_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='events',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Event'),
        ),
    ]
