# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_scenario_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Event'),
        ),
    ]
