# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_turn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_length',
            field=models.DurationField(default=datetime.timedelta(1)),
        ),
    ]
